## Numpy

Numpy is a fundamental library for scientific computing in Python. Provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures

In [2]:
!pip install numpy

In [3]:
import numpy as np

## create array using numpy
## 1D array
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) ## 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [5]:
arr2=np.array([[1,2,3,4,5]])

In [6]:
arr2.shape

(1, 5)

In [8]:
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
np.arange(0,10,2).reshape(5,1) ## arange- create array with step size in a range

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [12]:
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
## identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Array:\n",arr)
print("Shape:",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Data type:",arr.dtype)
print("Item size:",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Number of dimensions: 2
Data type: int64
Item size: 8


In [17]:
### Numpy vectorized operations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

### Element wise addition

print("Addition:",arr1+arr2)
print("Subtraction:",arr1-arr2)
print("Multiplication:",arr1*arr2)
print("Division:",arr1/arr2)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [18]:
## Universal function
arr=np.array([2,3,4,5,6])
print(np.sqrt(arr))  # square root
print(np.exp(arr))   # exponential
print(np.log(arr))   # natural logarithm
print(np.sin(arr))   # sine function

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


In [19]:
## array slicing and indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Original Array:\n",arr)

Original Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
arr[0]

array([1, 2, 3, 4])

In [24]:
print(arr[0][0])
print(arr[0:2,2:])
print(arr[1:,2:])

1
[[3 4]
 [7 8]]
[[ 7  8]
 [11 12]]


In [22]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [25]:
## Modify array elements
arr[0,0]=99
print(arr)

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
arr[1:]=100
print(arr)

[[ 99   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [27]:
## Statistical concepts - Normalization
data=np.array([1,2,3,4,5,6,7,8,9,10])
mean=np.mean(data)
std=np.std(data)
normalized_data=(data-mean)/std
print("Original Data:",data)
print("Mean:",mean)
print("Standard Deviation:",std)
print("Normalized Data:",normalized_data)

Original Data: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Standard Deviation: 2.8722813232690143
Normalized Data: [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
  0.52223297  0.87038828  1.21854359  1.5666989 ]


In [28]:
data=np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [29]:
data[data>5]

array([ 6,  7,  8,  9, 10])